### ISSUE TITLE
problems with case sensitivity on login/account creation with azure

### ISSUE THREAD

**Issue by BenKelada** [Microsoft/moodle-auth_oidc#6]
Moodle lower cases usernames  when creating accounts
when using a postgres database comparisons/collations are cases sensitive (they are case insensitive on mysql / mssql by default )
this means that when using this plugin with an azure account with uppercase characters in the username user account creation works but logins failed
this change fixes it:
```
--- moodle/auth/oidc/classes/loginflow/authcode.php	(date 1448580884000)
+++ moodle/auth/oidc/classes/loginflow/authcode.php	(revision )
@@ -289,8 +289,9 @@
             // Use 'upn' if available for username (Azure-specific), or fall back to lower-case oidcuniqid.
             $username = $idtoken->claim('upn');
             if (empty($username)) {
-                $username = strtolower($oidcuniqid);
+                $username = $oidcuniqid;
             }
+            $username = strtolower($username);
             $tokenrec = $this->createtoken($oidcuniqid, $username, $authparams, $tokenparams, $idtoken);
         }
 ```

**Comment by jamesmcq** [comment]
Thanks Ben - I've added this patch to our backlog, we'll be reviewing it and the issue you reported in greater depth soon.

**Comment by BenKelada** [comment]
Hi James,
any love on this issue? is this the right spot for reporting i notice issues are also being tracked over here: https://github.com/Microsoft/o365-moodle/issues
cheers,
Ben

**Comment by jamesmcq** [comment]
Hi Ben, Sorry for being a little quiet on this - this is scheduled for our next release. Thanks again for submitting!

**Comment by BenKelada** [comment]
No worries thanks james

**Comment by jamesmcq** [comment]
Thanks Ben - I've added your patch into our dev repository at https://github.com/Microsoft/o365-moodle. Your patch is in branches [wip-MSFTMPP-340-m30](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-340-m30), [wip-MSFTMPP-340-m29](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-340-m29), [wip-MSFTMPP-340-m28](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-340-m28), [wip-MSFTMPP-340-m27](https://github.com/Microsoft/o365-moodle/commits/wip-MSFTMPP-340-m27). This will be included in our next release.
