### ISSUE TITLE
case sensitive in pgsql

### ISSUE THREAD

**Issue by leonhedding** [Microsoft/moodle-auth_oidc#9]
I am using this plugin to allow for authentication into our Moodle install from O365. Our Moodle is installed using pgsql which is case sensitive. This is causing nothing but problems when we go to migrate from an ldap import which uses SAMAccountName to the UPN format in O365. The main problem is that the UPN's in O365 are Firstname.Lastname@domain.com and the usernames that are stored in Moodle are firstname.lastname.

What I am finding happen is that Moodle keeps creating new accounts because the case sensitive nature of pgsql and the fact that this plugin does not take this into account. The UPN which gets stored in the username and oidcusername fields from the mdl_auth_oidc_token table is in the Firstname.Lastname@domain.com format and this does not then match the username of firstname.last@domain.com in the mdl_user table. We then get new accounts created.

I have tried to use the mdl_local_o365_connections table to link the Moodle user accounts to the O365  user accounts, but this is not working as expected. What happens is duplicate accounts get created (because of the case sensitive nature of pgsql. Or if I login slightly differently into Moodle I am told that my users need to login first as the LDAP auth method, manually enable O365 authentication and then I can get O365 authentication working.

It is really a mess and not something I can let my users try to understand as I struggle to understand it.

So, the working fix I have is to make the username in table mdl_auth_oidc_token lowercase. Having the oidcusername  field lowercase is not required I don't think. If the username field is not lower then the match between mdl_user and mdl_auth_oidc_token requires the mdl_local_o365_connections table and that the code surrounding the use of that table gives all sorts of errors because it assumes case insensitive searches when querying for usernames.

**Comment by jamesmcq** [comment]
Thanks for the report - had this reported here as well: https://github.com/Microsoft/moodle-auth_oidc/issues/6

A fix is has been completed and is scheduled for the next release. Once it's out (should be a day or two), can you try it out? If you're still experiencing problems please let me know (re-open this or create a new issue) - Thanks!
